server:
  port: 8016
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/wanted
    username: wanted
    password: preonboarding
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
